walmart_dbt_project:
  outputs:
    dev:
      catalog: walmart
      host: 'your-databricks-host'
      http_path: /sql/1.0/warehouses/d1840b15315bcd74
      schema: dbt_schema
      threads: 1
      token: 'your-databricks-token'
      type: databricks
  target: dev
